index.js
test/index.test.js

- Remove `null` values in returns as our validation considers it bad output.
- Removing special casing for Postgres as we use mixed array cases (not always string, sometimes object).

Correct usage of Postgres and Null values

---

package.json

Currently `sequelize` requires mysql module not mysql2. 
screwdriver-cd/screwdriver#325

Use mysql instead of mysql2

---

index.js
test/index.test.js

MySQL requires that an indexed column including primary key is fixed length.
Sequelize will generate a DDL with no length option if we specify `Sequelize.TEXT` as data type.
Screwdriver mainly uses string hash as ID, so the current version  doesn't work with MySQL. (screwdriver-cd/screwdriver#325)
This PR fixes this issue by using `Sequelize.STRING(len)` for fixed-length string column.

Use Sequelize.STRING with length

---

index.js
package.json
test/.eslintrc.yaml
test/index.test.js

- Lookup without ID if not provided
- Save no longer requires `id`
- Update takes new format
- Add auto-incrementing and unique keys
BREAKING CHANGE: Requires an improved input for save and update
Epic: https://github.com/screwdriver-cd/screwdriver/issues/399
Blocked By: 
- https://github.com/screwdriver-cd/data-schema/pull/98 (merged)
- https://github.com/screwdriver-cd/datastore-base/pull/24 (merged)

feat(399): switch to numbers instead of hashes

---

index.js
test/index.test.js

Beta is currently failing because launcher fails to unmarshall. The eventId and jobId are string when we read back from datastore here: https://github.com/screwdriver-cd/datastore-sequelize/blob/master/index.js#L348 
Changing this to `DOUBLE` fixes it
Related: https://github.com/screwdriver-cd/screwdriver/issues/399

fix: change DECIMAL to DOUBLE

---

index.js
package.json
test/index.test.js

Context:
========
Sequelize 4.x adds a feature to do `ALTER TABLE` when performing a `sync()`. This should allow us to dynamically update table columns.
Objective:
----------
Update sequelize so we can update tables without dropping and recreating them.

feat: update to sequelize 4

---

package.json

The previous commit was a major version bump, but we forgot to include "BREAKING CHANGE" in the commit message. So, this is a non-breaking and non-major commit, but necessary to publish a bumped version in npm.

feat(545): Add reetika. BREAKING CHANGE: prev commit was breaking

---

index.js
test/index.test.js

I found that this module doesn't work with Sequelize@^4.0.0 when `prefix` is set.
There is a process which joins `prefix` and `column` with `.` in sequelize.
https://github.com/sequelize/sequelize/blob/v4.4.2/lib/dialects/abstract/query-generator.js#L2344
In v4.4.2, query generator in each dialect calls `whereQuery` with `options` which includes `prefix` key from dataschema-sequelize, so it generates a broken query like `WHERE myprefix_.id = 1`.
https://github.com/sequelize/sequelize/blob/v4.4.2/lib/dialects/sqlite/query-generator.js#L242
But v3.30.4 calls it without `options` object, so it generates a query like `WHERE id = 1`.
https://github.com/sequelize/sequelize/blob/v3.30.4/lib/dialects/sqlite/query-generator.js#L152
There is no document described about `prefix` option, so I've …

fix: Don't pass prefix config to Sequelize

---

package.json

Sequelize@4 was introduced by #18. It requires `mysql2` module instead of `mysql`.
I confirmed that `mysql2` module works well by customizing Dockerfile like below.
```
RUN cd /usr/src/app && npm install mysql2
```

Fix: Replace mysql with mysql2

---

screwdriver.yaml

`mysql2` is included in https://github.com/screwdriver-cd/datastore-sequelize/pull/23 but this package has not been published yet.

fix: use semantic-release template

---

index.js
package.json
test/index.test.js

Currently, pagination has not been implemented yet for `datastore-sequelize`. @catto has created an issue reporting that there is a substantial delay when fetching pipeline data from the API. As scalability is one of Screwdriver's main goals, it's critical that we address this issue.
Add implementation for pagination for `myFactory.list()`:
```js
pipelineFactory.list({
pagination: {
page: 1,
count: 50
}
})
```
* Issue: https://github.com/screwdriver-cd/screwdriver/issues/880

feat(880): Add pagination for sequelize datastore

---

index.js
package.json
test/index.test.js

The API pulled in the sequelize datastore changes because it wasn't a breaking change. The UI doesn't support pagination yet, so pagination should be reverted to fix it. After reverting, a new PR will be created and flagged as a breaking change.
Revert the pagination feature for the datastore to fix the UI.

fix: Revert pagination for sequelize datastore

---

index.js
test/index.test.js

Users should be able to specify which field they want to sort by when queries are returned from the DB.
This PR changes the sortKey to the `sortBy` field if it is provided. It can be any string, default will be set to `id`.
Should be able to sort by a JSON nested field according to this ticket: https://stackoverflow.com/questions/47213802/sequelize-query-with-order-by-a-field-in-jsonb-object
Example here: https://github.com/sequelize/sequelize/blob/master/test/integration/model/json.test.js#L588
Related to https://github.com/screwdriver-cd/screwdriver/issues/880
Blocked by https://github.com/screwdriver-cd/data-schema/pull/274

feat(880): Allow sort by sortBy field [2]

---

index.js
package.json
test/index.test.js

Since we're adding pagination for pipelines, we can no longer have search functionality stored in the UI. 
This PR adds search capability for the datastore.
To do a search, it expects a param like this:
```
params: {
search: {
field: "scmRepo",
term: "%name%Screwdriver%"
}
}
```
It will first validate that the field `scmRepo` exists in the pipelines table then search for the term `Screwdriver` in the `scmRepo` field.
Related to https://github.com/screwdriver-cd/screwdriver/issues/880
Blocked by https://github.com/screwdriver-cd/data-schema/pull/278

feat(880): Add search capability for scan [2]

---

index.js
package.json
test/index.test.js

There are many improvements to be made on the templates/commands pages. It would be nice if we had built-in search capabilities. 
The redesign would allow users to choose a `namespace` from a dropdown of all template `namespaces`. This requires a new endpoint and datastore support (distinct column search).
The redesign also would allow users to search by keyword such as `nodejs` through all template `name`, `namespace`, and `description` fields. This requires datastore support (multiple field search).
This PR adds support for distinct column search and multiple field search.
Given a config like:
```
{
params: {
distinct: 'namespace'
}
}
```
Returns all distinct `namespace` rows. [Sequelize documentation.](https://stackoverflow.com/a/45010576)
Given a config like:
```
{
search: {
field: …
```

feat(1271): Add support for distinct column search and multiple field search [2]

---

index.js
package.json
test/index.test.js

Allows scanning for time range. `startTime` and `endTime` will be passed in by models (https://github.com/screwdriver-cd/models/pull/319) when trying to look for records within a time range. 
Related:
https://github.com/screwdriver-cd/screwdriver/issues/1412

feat(1412): add compare timerange

---

index.js
package.json

I added log function so that users can determine which query is slow and see what alter query are issued.
Query execution time will be passed to the second argument of logger function if `benchmark` option is enabled.
The first argument is just a message including a query.
https://github.com/sequelize/sequelize/blob/8df9b8f3c8ff15427d8adbeb2c712dfe7df694d4/lib/dialects/mysql/query.js#L63
Reference:
http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

fix: Output alter and slow query logs

---

index.js

sd api pods crashing due to index rebuilding. will separate out index creation process. disabling index creation via sequelize

fix: remove index creation

---

index.js
package.json
test/index.test.js

For events & pipelines, we can use `createTime` to filter time range
For steps, there is no `createTime`. For filtering, we should use `startTime` field instead. This PR allows flexibility to filter time using a different key. 
I call this field `timeKey`, but I'm open to suggestion on what's a good name for this field. 
Related: 
https://github.com/screwdriver-cd/screwdriver/issues/1412

fix: allow time based filtering using a different key

---

index.js
test/index.test.js

Should be `iLike`, not `ilike`. 
Related: https://github.com/screwdriver-cd/screwdriver/issues/1272

fix: iLike with uppercase L

---

index.js
package.json
test/index.test.js

- update sequelize to 5.3.x to fix security vulnerability
- I have checked the breaking changes in the release doc for v5 and fixed it in our code accordingly: https://github.com/sequelize/sequelize/releases/tag/v5.1.0
PR opened by Snyk: https://github.com/screwdriver-cd/datastore-sequelize/pull/50

fix: update sequelize to 5.3.x to fix security vulnerability

---

package.json
screwdriver.yaml

move to postinstall script
Related: https://github.com/screwdriver-cd/datastore-sequelize/pull/56

fix: move sqlite3 to postinstall script

---

index.js
test/index.test.js

Screwdriver database DDL changes are applied during Screwdriver api startup, which leads to api experiencing slowness or goes to the unreachable state. This does table-level exclusive locks because of 1. DDL statements are executed in parallel from multiple pods and 2. ALTER statements are executed even though no changes made to the database schema. Root-cause for this issue is calling Sequelize sync method with { alter: true } parameter.
This PR addresses sequelize ddl sync required or optional based on an environment variable setting.
https://github.com/screwdriver-cd/screwdriver/issues/1664
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution …

feat(1664): make sequalize ddl sync optional

---

index.js
test/index.test.js

`meta` object is defined as `TEXT` type in MySQL.
The data size of `TEXT` type in MySQL is limited in 64KB, but the `meta` data tend to be bigger because it includes various items (e.g. `commit.changedFiles` may have many files and each file may be very long file name). And the meta has being empty object if the size is over. We have had such situation.
This extends the data size of columns defined as `object` in data-schema from `TEXT`(64KB in MySQL) to `MEDIUMTEXT`(16MB in MySQL) if the Database supports `MEDIUMTEXT`.
- => https://github.com/screwdriver-cd/data-schema/pull/356
https://github.com/screwdriver-cd/screwdriver/issues/1763
https://sequelize.org/master/class/lib/data-types.js~TEXT.html
I confirm that this contribution is made under the terms of the license found in the root …

fix(1763): extends the data size of object from `TEXT` to `MEDIUMTEXT`

---

index.js
test/index.test.js

This pr is that discussed in this issue.
https://github.com/screwdriver-cd/screwdriver/issues/1723
Current templates and commands page shows  the template with `MAX`.
It should shows template and command that sorted by createTime. However, in order to get the version number of the latest template, there are cases where it is not possible to use `createTime`, so I adopted `id`. I fixed to use below SQL.
```
> SELECT id, name, namespace ...
FROM templates 
WHERE templates.id = (
SELECT MAX(t.id) 
FROM templates AS t 
WHERE templates.name = t.name 
AND templates.namespace = t.namespace 
AND templates.id <= t.id
) 
ORDER BY createTime ... ;
+----+-------+-------------+---------+------------+
| id | name  | namespace   | version | createTime | …
```

fix(1723): Change the query to the last updated

---

index.js

log level is not setup properly.
Use LOG_LEVEL env var for loggin

fix: use LOG_LEVEL for winston

---

index.js

Subquery call is not using prefix for referring table name. 
Use proper table prefix when subquery is constructed. 
https://github.com/screwdriver-cd/datastore-sequelize/pull/59/files#issuecomment-561554294

fix: use proper prefix in subquery

---

index.js
test/index.test.js

When Joi.alternatives() is used, Sequelize data type is returned as null, which leads to TypeError: Cannot read property 'key' of null
Return Sequelize.TEXT('medium') data type for Joi.alternatives().
[1710](https://github.com/screwdriver-cd/screwdriver/issues/1710)

fix(1710): fix type key null for Joi.alternatives()

---

index.js

This PR fixes the issue below.  
https://github.com/screwdriver-cd/screwdriver/issues/1857
The trusted mark is disappeared by the PR below.  
https://github.com/screwdriver-cd/datastore-sequelize/pull/59
That is because the trusted value is assigned only first version of template.
This PR fixes the issue by refer the MAX value of trusted column.
The SQL is like below.
```sql
SELECT
id,
name,
version,
namespace,
(
-- Start the new subquery that this PR add.
SELECT
MAX(trusted)
FROM
templates
WHERE
t1.name = name
AND t1.namespace = namespace
-- End the new subquery
) AS trusted
FROM
templates AS t1
WHERE
t1.id IN (
SELECT
MAX(t2.id)
FROM
templates AS t2
WHERE
t1.name = t2.name
AND t1.namespace = t2.namespace
AND t1.id <= t2.id
)
ORDER BY
createTime;
```
This PR seems to be temporary because …

fix(1857): Show trusted mark on templates/commands list screen

---

index.js
test/index.test.js

I filed to apply screwdriver-api `v0.5.820` for this error.
```
{"message":"Datastore ddl sync enabled: true","level":"info","timestamp":"2020-01-06T03:58:44.586Z"}
{"name":"SequelizeDatabaseError","parent":{"code":"ER_BLOB_KEY_WITHOUT_LENGTH","errno":1170,"sqlState":"42000","sqlMessage":"BLOB/TEXT column 'src' used in key specification without a key length","sql":"CREATE TABLE IF NOT EXISTS `triggers` (`id` INTEGER UNSIGNED auto_increment , `src` MEDIUMTEXT, `dest` MEDIUMTEXT, UNIQUE `uniquerow` (`src`, `dest`), PRIMARY KEY (`id`)) ENGINE=InnoDB;"},"original":{"code":"ER_BLOB_KEY_WITHOUT_LENGTH","errno":1170,"sqlState":"42000","sqlMessage":"BLOB/TEXT column 'src' used in key specification without a key length","sql":"CREATE TABLE IF NOT EXISTS `triggers` (`id` INTEGER UNSIGNED …
```

fix: Use Sequelize.STRING with length

---

package.json
screwdriver.yaml

Screwdriver API is running on node:12 container which is no longer supported.
Upgrade to latest LTS of node. 
https://github.com/screwdriver-cd/screwdriver/issues/1722
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

fix: use node:12 container

---

index.js
test/index.test.js

This change is to improve api efficiency when querying for template popularity metrics.
This PR adds the ability to do aggregation queries.
https://github.com/screwdriver-cd/screwdriver/issues/1091

feat(1091): add ability to do aggregation query

---

index.js
test/index.test.js

Need to remove the order by portion of aggregation queries so that they will work correctly in postgres. order by is defaulted to id (and then possibly updated to a different index field) in _scan, if you are not selecting this field in the aggregation query it breaks the query.
i.e. What the queries look like:
Before:
SELECT "templateId", COUNT("templateId") AS count FROM jobs AS jobs WHERE jobs."templateId" IN ('3','5') GROUP BY "templateId" ORDER BY "id";
After:
SELECT "templateId", COUNT("templateId") AS count FROM jobs AS jobs WHERE jobs."templateId" IN ('3','5') GROUP BY "templateId";
Remove order from findParams; that is remove the order by portion of aggregation queries.
https://github.com/screwdriver-cd/screwdriver/issues/1091
I confirm that this contribution is made under the …

fix(1091): fix aggregation queries by deleting order by param

---

index.js
package.json
test/index.test.js

Need to add the ability to do raw queries to datastore so queries that are otherwise impossible to do through sequelize can be done.
Add a query method to datastore.
https://github.com/screwdriver-cd/screwdriver/issues/1967

feat(1967): add ability to do raw queries. BREAKING CHANGE: pulling in new datastore-base version

---

index.js
package.json
test/index.test.js

Screwdriver hapi.js dependencies are outdated and not supported anymore.
This PR majorly upgrades @hapi/joi version and fixes all schema related changes to be compatible with latest @hapi js dependencies.
https://github.com/screwdriver-cd/screwdriver/issues/1958

feat(1958): Hapi v19 dependencies upgrade. BREAKING CHANGE: v19.x.x

---

package.json

I want fix an issue with the template page not displaying anything.
https://github.com/screwdriver-cd/screwdriver/issues/2212.
We previously updated to sequelize@6, but it seems that some support is missing.
https://github.com/screwdriver-cd/datastore-sequelize/commit/138131b0ee52a6301fb766237329d3cbc415bb69#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L58-R58
One way to deal with this is to revert to sequelize@5.
https://www.npmjs.com/package/sequelize

fix(2212): sequelize version to 5.22.3

---

index.js
package.json
test/index.test.js

[Sequelize](https://github.com/screwdriver-cd/datastore-sequelize/blob/b4609dc1ccb38888b26afc2f048f5f9cec6b6bb5/index.js#L27) library uses joi.object().describe() to get all the keys that are there in the model, profiling the sd node process has showed that this heavily used function takes up a lot of the processing time due to the nature of it describe a huge joi object on the entire model which leads to performance issues. Solution to fix this is to get rid of it as it seems unnecessary to use the entire nested object here as we only want to fetch the type of the properties.
This PR removes the use of .describe() on entire model objects and instead uses the fields property where required to avoid any querying.
https://github.com/screwdriver-cd/screwdriver/issues/2216
I confirm that this …

feat: remove expensive describe() fn calls and use fields property instead

---

index.js

Query fails for postgress when using `ilke` symbol for integer keyword
Use eq symbol instead
https://github.com/screwdriver-cd/screwdriver/issues/2267

fix(2267): use eq instead of ilike for integer keyword

---

index.js
test/index.test.js

It would be nice to return total count in addition to paginated content.
add support to return total count
https://github.com/screwdriver-cd/screwdriver/issues/2312

fix(2312): add ability to return total record count in scan

---

index.js
test/index.test.js

currently scan query with OR field will overwrite AND fields
AND fields should not be overwritten
https://github.com/screwdriver-cd/screwdriver/issues/2312

fix(2312): scan OR fields should not overwrite AND fields

---

index.js

Sequalize model name is set as the table name. So when Sequalize model look happens
prefix must be used.
Sequalize model names are not the same as SD Model names.
https://github.com/screwdriver-cd/screwdriver/issues/2526

fix(2526): fix model lookup when prefix is used.

---

index.js
test/index.test.js

In PostgreSQL, `count()` returns of type `bigint`.
Sequelize uses [Node Postgres](https://node-postgres.com/) under the hood to interface with PostgreSQL database.
By default, Node Postgres casts `bigint` to `string`.
https://github.com/brianc/node-pg-types/blob/master/lib/binaryParsers.js#L105
https://github.com/charmander/pg-int8
Changes made in this PR https://github.com/screwdriver-cd/ui/pull/937 to display aggregated usage metrics across all the template versions assumes API always returns the count as number.
This works as expected for MySQL.
For PostgreSQL, the values are concatenated which results in incorrect values displayed in the UI.
Configure Node Postgres not to cast `bigint` to `string`.
https://github.com/brianc/node-postgres/pull/427 …

feat(2862): Return aggregation value as number instead as string for PostgreSQL

---

index.js
test/index.test.js

Currently a lot of calls are being made on the PR tab page in the UI to: 
- `GET /pipelines/:id/events?count=1&page=1&prNum=prNum`
- `GET /jobs/:id/builds?count=10&page=1`
- `GET /events/:id/builds`
It would be nice if we could simplify these calls to get only latest builds in a PR and make fewer calls to the API.
This PR adds a new flag `inverse` that will use `notILike` or `notLike` to search.
Related to https://github.com/screwdriver-cd/screwdriver/pull/3078
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

feat: Add notILike and notLike to search

---

package.json

The following vulnerability has been detected by Snyk.
https://www.cve.org/CVERecord?id=CVE-2024-21508
We eliminate vulnerabilities.
`sequelize` is compatible with the new `mysql2`
https://sequelize.org/docs/v6/other-topics/dialect-specific-things/#mysql

fix: bump mysql2 version

---

index.js
test/index.test.js

It would be nice if we could use the greater than or less than operators in our queries.
This PR adds the `Sequelize.Op.gt` and `Sequelize.Op.lt` operators for query params (numbers only).
Related to https://github.com/screwdriver-cd/screwdriver/issues/3163, https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#operators

feat(3163): Handle params with greater than or less than filter [1]
